# Task
Load the 'Global_Weather_Repository.csv' dataset, perform comprehensive data cleaning and preprocessing including handling missing values and inconsistencies, converting units, normalizing values, and aggregating data, then generate a summary document of data quality and save the cleaned dataset as 'cleaned_global_weather_data.csv' to prepare it for further analysis.

## Setup Environment and Load Data

In [151]:
import pandas as pd

df = pd.read_csv('master_dataset.csv')
df.head(5)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [152]:
print(df.shape)
df.info()

(107378, 41)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107378 entries, 0 to 107377
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       107378 non-null  object
 1   location_name                 107378 non-null  object
 2   latitude                      107378 non-null  float64
 3   longitude                     107378 non-null  float64
 4   timezone                      107378 non-null  object
 5   last_updated_epoch            107378 non-null  int64
 6   last_updated                  107378 non-null  object
 7   temperature_celsius           107378 non-null  float64
 8   temperature_fahrenheit        107378 non-null  float64
 9   condition_text                107378 non-null  object
 10  wind_mph                      107378 non-null  float64
 11  wind_kph                      107378 non-null  float64
 12  wind_degree                   107378 non-null  int64
 13  wind_direction                107378 non-null  object
 14  pressure_mb                   107378 non-null  float64
 15  pressure_in                   107378 non-null  float64
 16  precip_mm                     107378 non-null  float64
 17  precip_in                     107378 non-null  float64
 18  humidity                      107378 non-null  int64
 19  cloud                         107378 non-null  int64
 20  feels_like_celsius            107378 non-null  float64
 21  feels_like_fahrenheit         107378 non-null  float64
 22  visibility_km                 107378 non-null  float64
 23  visibility_miles              107378 non-null  float64
 24  uv_index                      107378 non-null  float64
 25  gust_mph                      107378 non-null  float64
 26  gust_kph                      107378 non-null  float64
 27  air_quality_Carbon_Monoxide   107378 non-null  float64
 28  air_quality_Ozone             107378 non-null  float64
 29  air_quality_Nitrogen_dioxide  107378 non-null  float64
 30  air_quality_Sulphur_dioxide   107378 non-null  float64
 31  air_quality_PM2.5             107378 non-null  float64
 32  air_quality_PM10              107378 non-null  float64
 33  air_quality_us-epa-index      107378 non-null  int64
 34  air_quality_gb-defra-index    107378 non-null  int64
 35  sunrise                       107378 non-null  object
 36  sunset                        107378 non-null  object
 37  moonrise                      107378 non-null  object
 38  moonset                       107378 non-null  object
 39  moon_phase                    107378 non-null  object
 40  moon_illumination             107378 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 33.6+ MB

## Inspect Dataset Structure and Data Types

In [153]:
df.info()
df.head()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107378 entries, 0 to 107377
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       107378 non-null  object
 1   location_name                 107378 non-null  object
 2   latitude                      107378 non-null  float64
 3   longitude                     107378 non-null  float64
 4   timezone                      107378 non-null  object
 5   last_updated_epoch            107378 non-null  int64
 6   last_updated                  107378 non-null  object
 7   temperature_celsius           107378 non-null  float64
 8   temperature_fahrenheit        107378 non-null  float64
 9   condition_text                107378 non-null  object
 10  wind_mph                      107378 non-null  float64
 11  wind_kph                      107378 non-null  float64
 12  wind_degree                   107378 non-null  int64
 13  wind_direction                107378 non-null  object
 14  pressure_mb                   107378 non-null  float64
 15  pressure_in                   107378 non-null  float64
 16  precip_mm                     107378 non-null  float64
 17  precip_in                     107378 non-null  float64
 18  humidity                      107378 non-null  int64
 19  cloud                         107378 non-null  int64
 20  feels_like_celsius            107378 non-null  float64
 21  feels_like_fahrenheit         107378 non-null  float64
 22  visibility_km                 107378 non-null  float64
 23  visibility_miles              107378 non-null  float64
 24  uv_index                      107378 non-null  float64
 25  gust_mph                      107378 non-null  float64
 26  gust_kph                      107378 non-null  float64
 27  air_quality_Carbon_Monoxide   107378 non-null  float64
 28  air_quality_Ozone             107378 non-null  float64
 29  air_quality_Nitrogen_dioxide  107378 non-null  float64
 30  air_quality_Sulphur_dioxide   107378 non-null  float64
 31  air_quality_PM2.5             107378 non-null  float64
 32  air_quality_PM10              107378 non-null  float64
 33  air_quality_us-epa-index      107378 non-null  int64
 34  air_quality_gb-defra-index    107378 non-null  int64
 35  sunrise                       107378 non-null  object
 36  sunset                        107378 non-null  object
 37  moonrise                      107378 non-null  object
 38  moonset                       107378 non-null  object
 39  moon_phase                    107378 non-null  object
 40  moon_illumination             107378 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 33.6+ MB

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,107378.00000,107378.000000,1.073780e+05,107378.00000,107378.000000,107378.000000,107378.000000,107378.000000,107378.000000,107378.000000,...,107378.000000,107378.000000,107378.000000,107378.000000,107378.000000,107378.000000,107378.000000,107378.000000,107378.000000,107378.000000
mean,19.16825,22.047441,1.739749e+09,22.54885,72.589697,8.150644,13.120647,170.690737,1014.036944,29.943845,...,18.358329,499.725732,61.271043,15.595602,10.953524,25.298204,51.319241,1.731733,2.688120,49.934651
std,24.44401,65.803704,1.379054e+07,8.87527,15.975296,7.654393,12.315899,102.732012,11.028377,0.325624,...,14.349085,819.515952,31.778907,25.363015,39.118505,39.472626,158.495265,0.965628,2.516134,35.047069
min,-41.30000,-175.200000,1.715849e+09,-24.90000,-12.800000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.75000,-6.836100,1.727861e+09,17.40000,63.300000,4.000000,6.500000,83.000000,1010.000000,29.830000,...,10.400000,225.850000,41.000000,1.480000,0.925000,7.215000,10.400000,1.000000,1.000000,15.000000
50%,17.25000,23.316700,1.739787e+09,24.40000,75.900000,6.900000,11.200000,164.000000,1013.000000,29.930000,...,15.700000,318.200000,58.000000,5.180000,2.405000,14.615000,21.100000,1.000000,2.000000,50.000000
75%,40.40000,50.580000,1.751705e+09,28.20000,82.800000,11.200000,18.000000,256.000000,1018.000000,30.060000,...,24.300000,493.950000,78.000000,17.945000,8.880000,28.700000,43.845000,2.000000,3.000000,85.000000
max,64.15000,179.220000,1.763536e+09,49.20000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

## Identify Missing Values and Anomalies

In [154]:
df.isnull().sum()

anomalous_columns = [
    'air_quality_Carbon_Monoxide',
    'air_quality_Sulphur_dioxide',
    'air_quality_PM10',
    'wind_mph',
    'wind_kph',
    'gust_mph',
    'gust_kph',
    'pressure_mb',
    'pressure_in'
]

for col in anomalous_columns:
    print(f"{col}: Min = {df[col].min()}, Max = {df[col].max()}")

print(f"'air_quality_Carbon_Monoxide' with -9999: {(df['air_quality_Carbon_Monoxide'] == -9999).sum()} occurrences")
print(f"'air_quality_Sulphur_dioxide' with -9999: {(df['air_quality_Sulphur_dioxide'] == -9999).sum()} occurrences")
print(f"'air_quality_PM10' with -1848.15: {(df['air_quality_PM10'] == -1848.15).sum()} occurrences")

air_quality_Carbon_Monoxide: Min = -9999.0, Max = 38879.398
air_quality_Sulphur_dioxide: Min = -9999.0, Max = 521.33
air_quality_PM10: Min = -1848.15, Max = 6037.29
wind_mph: Min = 2.2, Max = 1841.2
wind_kph: Min = 3.6, Max = 2963.2
gust_mph: Min = 2.2, Max = 1845.7
gust_kph: Min = 3.6, Max = 2970.4
pressure_mb: Min = 947.0, Max = 3006.0
pressure_in: Min = 27.96, Max = 88.77
'air_quality_Carbon_Monoxide' with -9999: 1 occurrences
'air_quality_Sulphur_dioxide' with -9999: 1 occurrences
'air_quality_PM10' with -1848.15: 1 occurrences

In [155]:
import numpy as np

df.loc[df['air_quality_Carbon_Monoxide'] == -9999, 'air_quality_Carbon_Monoxide'] = np.nan
df.loc[df['air_quality_Sulphur_dioxide'] == -9999, 'air_quality_Sulphur_dioxide'] = np.nan
df.loc[df['air_quality_PM10'] == -1848.15, 'air_quality_PM10'] = np.nan

anomalous_columns = [
    'air_quality_Carbon_Monoxide',
    'air_quality_Sulphur_dioxide',
    'air_quality_PM10',
    'wind_mph',
    'wind_kph',
    'gust_mph',
    'gust_kph',
    'pressure_mb',
    'pressure_in'
]
for col in anomalous_columns:
    print(f"{col}: Min = {df[col].min()}, Max = {df[col].max()}")

air_quality_Carbon_Monoxide: Min = 72.85, Max = 38879.398
air_quality_Sulphur_dioxide: Min = 0.0, Max = 521.33
air_quality_PM10: Min = 0.168, Max = 6037.29
wind_mph: Min = 2.2, Max = 1841.2
wind_kph: Min = 3.6, Max = 2963.2
gust_mph: Min = 2.2, Max = 1845.7
gust_kph: Min = 3.6, Max = 2970.4
pressure_mb: Min = 947.0, Max = 3006.0
pressure_in: Min = 27.96, Max = 88.77

In [156]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     1
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     1
air_quality_PM2.5               0
air_quality_PM10                1
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [157]:
print(df[['air_quality_Carbon_Monoxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM10']].dtypes)

nan_rows_carbon_monoxide = df[df['air_quality_Carbon_Monoxide'].isna()]
nan_rows_sulphur_dioxide = df[df['air_quality_Sulphur_dioxide'].isna()]
nan_rows_pm10 = df[df['air_quality_PM10'].isna()]

if not nan_rows_carbon_monoxide.empty:
    print(nan_rows_carbon_monoxide[['country', 'location_name', 'air_quality_Carbon_Monoxide']])
else:
    print("No NaN values found in 'air_quality_Carbon_Monoxide' despite replacement.")

if not nan_rows_sulphur_dioxide.empty:
    print(nan_rows_sulphur_dioxide[['country', 'location_name', 'air_quality_Sulphur_dioxide']])
else:
    print("No NaN values found in 'air_quality_Sulphur_dioxide' despite replacement.")

if not nan_rows_pm10.empty:
    print(nan_rows_pm10[['country', 'location_name', 'air_quality_PM10']])
else:
    print("No NaN values found in 'air_quality_PM10' despite replacement.")

air_quality_Carbon_Monoxide    float64
air_quality_Sulphur_dioxide    float64
air_quality_PM10               float64
dtype: object
                  country location_name  air_quality_Carbon_Monoxide
5263  Antigua and Barbuda  Saint John's                          NaN
        country location_name  air_quality_Sulphur_dioxide
12078  Kiribati        Tarawa                          NaN
            country location_name  air_quality_PM10
55303  Saudi Arabia        Riyadh               NaN

In [158]:
affected_columns = [
    'air_quality_Carbon_Monoxide',
    'air_quality_Sulphur_dioxide',
    'air_quality_PM10'
]

for col in affected_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     1
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     1
air_quality_PM2.5               0
air_quality_PM10                1
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

## Handle Missing and Inconsistent Entries

In [159]:
import numpy as np

or_value = df.loc[0, 'air_quality_Carbon_Monoxide']
df.loc[0, 'air_quality_Carbon_Monoxide'] = np.nan

print(f"Value at df.loc[0, 'air_quality_Carbon_Monoxide'] set to: {df.loc[0, 'air_quality_Carbon_Monoxide']}")
print(f"'air_quality_Carbon_Monoxide' missing values count: {df['air_quality_Carbon_Monoxide'].isnull().sum()}")

df.loc[0, 'air_quality_Carbon_Monoxide'] = or_value
print(f"Value at df.loc[0, 'air_quality_Carbon_Monoxide'] reverted to: {df.loc[0, 'air_quality_Carbon_Monoxide']}")

Value at df.loc[0, 'air_quality_Carbon_Monoxide'] set to: nan
'air_quality_Carbon_Monoxide' missing values count: 2
Value at df.loc[0, 'air_quality_Carbon_Monoxide'] reverted to: 277.0

In [160]:
import numpy as np

df.loc[df['air_quality_Carbon_Monoxide'] == -9999, 'air_quality_Carbon_Monoxide'] = np.nan
df.loc[df['air_quality_Sulphur_dioxide'] == -9999, 'air_quality_Sulphur_dioxide'] = np.nan
df.loc[df['air_quality_PM10'] == -1848.15, 'air_quality_PM10'] = np.nan

df[['air_quality_Carbon_Monoxide', 'air_quality_Sulphur_dioxide', 'air_quality_PM10']].isnull().sum()

air_quality_Carbon_Monoxide    1
air_quality_Sulphur_dioxide    1
air_quality_PM10               1
dtype: int64

In [161]:
import numpy as np

wind_mph_threshold = 200
wind_kph_threshold = 320

pressure_mb_lower_threshold = 850
pressure_mb_upper_threshold = 1080
pressure_in_lower_threshold = 850 / 33.8639
pressure_in_upper_threshold = 1080 / 33.8639

df.loc[df['wind_mph'] > wind_mph_threshold, 'wind_mph'] = np.nan
df.loc[df['wind_kph'] > wind_kph_threshold, 'wind_kph'] = np.nan
df.loc[df['gust_mph'] > wind_mph_threshold, 'gust_mph'] = np.nan
df.loc[df['gust_kph'] > wind_kph_threshold, 'gust_kph'] = np.nan

df.loc[(df['pressure_mb'] < pressure_mb_lower_threshold) | (df['pressure_mb'] > pressure_mb_upper_threshold), 'pressure_mb'] = np.nan
df.loc[(df['pressure_in'] < pressure_in_lower_threshold) | (df['pressure_in'] > pressure_in_upper_threshold), 'pressure_in'] = np.nan

df[['wind_mph', 'wind_kph', 'gust_mph', 'gust_kph', 'pressure_mb', 'pressure_in']].isnull().sum()

wind_mph       1
wind_kph       1
gust_mph       1
gust_kph       1
pressure_mb    2
pressure_in    2
dtype: int64

In [162]:
imputation_columns = [
    'air_quality_Carbon_Monoxide',
    'air_quality_Sulphur_dioxide',
    'air_quality_PM10',
    'wind_mph',
    'wind_kph',
    'gust_mph',
    'gust_kph',
    'pressure_mb',
    'pressure_in'
]

print("Missing Values Before Imputation")
print(df[imputation_columns].isnull().sum())

for col in imputation_columns:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)

print("Missing Values After Imputation")
print(df[imputation_columns].isnull().sum())

Missing Values Before Imputation
air_quality_Carbon_Monoxide    1
air_quality_Sulphur_dioxide    1
air_quality_PM10               1
wind_mph                       1
wind_kph                       1
gust_mph                       1
gust_kph                       1
pressure_mb                    2
pressure_in                    2
dtype: int64
Missing Values After Imputation
air_quality_Carbon_Monoxide    0
air_quality_Sulphur_dioxide    0
air_quality_PM10               0
wind_mph                       0
wind_kph                       0
gust_mph                       0
gust_kph                       0
pressure_mb                    0
pressure_in                    0
dtype: int64

/tmp/ipython-input-4072835276.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)

In [163]:
imputation_columns = [
    'air_quality_Carbon_Monoxide',
    'air_quality_Sulphur_dioxide',
    'air_quality_PM10',
    'wind_mph',
    'wind_kph',
    'gust_mph',
    'gust_kph',
    'pressure_mb',
    'pressure_in'
]

print("Missing Values Before Imputation:")
print(df[imputation_columns].isnull().sum())

for col in imputation_columns:
    median_val = df[col].median()
    df[col] = df[col].fillna(median_val)

print("Missing Values After Imputation:")
print(df[imputation_columns].isnull().sum())

Missing Values Before Imputation:
air_quality_Carbon_Monoxide    0
air_quality_Sulphur_dioxide    0
air_quality_PM10               0
wind_mph                       0
wind_kph                       0
gust_mph                       0
gust_kph                       0
pressure_mb                    0
pressure_in                    0
dtype: int64
Missing Values After Imputation:
air_quality_Carbon_Monoxide    0
air_quality_Sulphur_dioxide    0
air_quality_PM10               0
wind_mph                       0
wind_kph                       0
gust_mph                       0
gust_kph                       0
pressure_mb                    0
pressure_in                    0
dtype: int64

###Convert units and normalize values.

In [164]:
datetime_columns = [
    'last_updated',
    'sunrise',
    'sunset',
    'moonrise',
    'moonset'
]

print("Data Types Before Datetime Conversion:")
print(df[datetime_columns].dtypes)

df['last_updated'] = pd.to_datetime(df['last_updated'], format='%Y-%m-%d %H:%M', errors='coerce')
for col in ['sunrise', 'sunset', 'moonrise', 'moonset']:
    df[col] = pd.to_datetime(df[col], format='%I:%M %p', errors='coerce')

print("Data Types After Datetime Conversion:")
print(df[datetime_columns].dtypes)

print(df[datetime_columns].head())

Data Types Before Datetime Conversion:
last_updated    object
sunrise         object
sunset          object
moonrise        object
moonset         object
dtype: object
Data Types After Datetime Conversion:
last_updated    datetime64[ns]
sunrise         datetime64[ns]
sunset          datetime64[ns]
moonrise        datetime64[ns]
moonset         datetime64[ns]
dtype: object
         last_updated             sunrise              sunset  \
0 2024-05-16 13:15:00 1900-01-01 04:50:00 1900-01-01 18:50:00
1 2024-05-16 10:45:00 1900-01-01 05:21:00 1900-01-01 19:54:00
2 2024-05-16 09:45:00 1900-01-01 05:40:00 1900-01-01 19:50:00
3 2024-05-16 10:45:00 1900-01-01 06:31:00 1900-01-01 21:11:00
4 2024-05-16 09:45:00 1900-01-01 06:12:00 1900-01-01 17:55:00

             moonrise             moonset
0 1900-01-01 12:12:00 1900-01-01 01:11:00
1 1900-01-01 12:58:00 1900-01-01 02:14:00
2 1900-01-01 13:15:00 1900-01-01 02:14:00
3 1900-01-01 14:12:00 1900-01-01 03:31:00
4 1900-01-01 13:17:00 1900-01-01 00:38:00

In [165]:
print("Data Type Before Categorical Conversion:")
print(df['moon_phase'].dtype)

df['moon_phase'] = df['moon_phase'].astype('category')

print("Data Type After Categorical Conversion:")
print(df['moon_phase'].dtype)

print(df['moon_phase'].head())

Data Type Before Categorical Conversion:
object
Data Type After Categorical Conversion:
category
0    Waxing Gibbous
1    Waxing Gibbous
2    Waxing Gibbous
3    Waxing Gibbous
4    Waxing Gibbous
Name: moon_phase, dtype: category
Categories (8, object): ['First Quarter', 'Full Moon', 'Last Quarter', 'New Moon', 'Waning Crescent',
                         'Waning Gibbous', 'Waxing Crescent', 'Waxing Gibbous']

In [166]:
imperial_columns_to_drop = [
    'temperature_fahrenheit',
    'wind_mph',
    'pressure_in',
    'precip_in',
    'visibility_miles',
    'gust_mph'
]

df = df.drop(columns=imperial_columns_to_drop)
print(df.head())

       country     location_name  latitude  longitude        timezone  \
0  Afghanistan             Kabul     34.52      69.18      Asia/Kabul
1      Albania            Tirana     41.33      19.82   Europe/Tirane
2      Algeria           Algiers     36.76       3.05  Africa/Algiers
3      Andorra  Andorra La Vella     42.50       1.52  Europe/Andorra
4       Angola            Luanda     -8.84      13.23   Africa/Luanda

   last_updated_epoch        last_updated  temperature_celsius condition_text  \
0          1715849100 2024-05-16 13:15:00                 26.6  Partly Cloudy
1          1715849100 2024-05-16 10:45:00                 19.0  Partly cloudy
2          1715849100 2024-05-16 09:45:00                 23.0          Sunny
3          1715849100 2024-05-16 10:45:00                  6.3  Light drizzle
4          1715849100 2024-05-16 09:45:00                 26.0  Partly cloudy

   wind_kph  ...  air_quality_PM2.5 air_quality_PM10  \
0      13.3  ...                8.4             26.6
1      11.2  ...                1.1              2.0
2      15.1  ...               10.4             18.4
3      11.9  ...                0.7              0.9
4      13.0  ...              183.4            262.3

   air_quality_us-epa-index  air_quality_gb-defra-index             sunrise  \
0                         1                           1 1900-01-01 04:50:00
1                         1                           1 1900-01-01 05:21:00
2                         1                           1 1900-01-01 05:40:00
3                         1                           1 1900-01-01 06:31:00
4                         5                          10 1900-01-01 06:12:00

               sunset            moonrise             moonset      moon_phase  \
0 1900-01-01 18:50:00 1900-01-01 12:12:00 1900-01-01 01:11:00  Waxing Gibbous
1 1900-01-01 19:54:00 1900-01-01 12:58:00 1900-01-01 02:14:00  Waxing Gibbous
2 1900-01-01 19:50:00 1900-01-01 13:15:00 1900-01-01 02:14:00  Waxing Gibbous
3 1900-01-01 21:11:00 1900-01-01 14:12:00 1900-01-01 03:31:00  Waxing Gibbous
4 1900-01-01 17:55:00 1900-01-01 13:17:00 1900-01-01 00:38:00  Waxing Gibbous

   moon_illumination
0                 55
1                 55
2                 55
3                 55
4                 55

[5 rows x 35 columns]

In [167]:
from sklearn.preprocessing import MinMaxScaler

columns_to_normalize = [
    'temperature_celsius',
    'wind_kph',
    'pressure_mb',
    'precip_mm',
    'humidity',
    'cloud',
    'visibility_km',
    'uv_index',
    'gust_kph',
    'air_quality_Carbon_Monoxide',
    'air_quality_Ozone',
    'air_quality_Nitrogen_dioxide',
    'air_quality_Sulphur_dioxide',
    'air_quality_PM2.5',
    'air_quality_PM10'
]

scaler = MinMaxScaler()

df[columns_to_normalize] = scaler.fit_transform(df[columns_to_normalize])

print(df[columns_to_normalize].head())
print(df[columns_to_normalize].describe())

   temperature_celsius  wind_kph  pressure_mb  precip_mm  humidity  cloud  \
0             0.695007  0.036113     0.488722   0.000000  0.224490   0.30
1             0.592443  0.028295     0.488722   0.002367  0.938776   0.75
2             0.646424  0.042815     0.481203   0.000000  0.275510   0.00
3             0.421053  0.030901     0.451128   0.007102  0.602041   1.00
4             0.686910  0.034996     0.481203   0.000000  0.887755   0.50

   visibility_km  uv_index  gust_kph  air_quality_Carbon_Monoxide  \
0         0.3125  0.429448  0.042422                     0.005261
1         0.3125  0.306748  0.053662                     0.003112
2         0.3125  0.306748  0.067803                     0.012056
3         0.0625  0.122699  0.036621                     0.002509
4         0.3125  0.490798  0.060189                     0.074502

   air_quality_Ozone  air_quality_Nitrogen_dioxide  \
0           0.214271                      0.002572
1           0.202413                      0.002104
2           0.025380                      0.152209
3           0.133971                      0.003741
4           0.039526                      0.169979

   air_quality_Sulphur_dioxide  air_quality_PM2.5  air_quality_PM10
0                     0.000384           0.005101          0.004378
1                     0.000192           0.000577          0.000303
2                     0.025703           0.006340          0.003020
3                     0.000384           0.000330          0.000121
4                     0.060422           0.113531          0.043420
       temperature_celsius       wind_kph    pressure_mb      precip_mm  \
count        107378.000000  107378.000000  107378.000000  107378.000000
mean              0.640335       0.035343       0.503758       0.003329
std               0.119774       0.031289       0.052059       0.014059
min               0.000000       0.000000       0.000000       0.000000
25%               0.570850       0.010797       0.473684       0.000000
50%               0.665317       0.028295       0.496241       0.000000
75%               0.716599       0.053611       0.533835       0.000710
max               1.000000       1.000000       1.000000       1.000000

            humidity          cloud  visibility_km       uv_index  \
count  107378.000000  107378.000000  107378.000000  107378.000000
mean        0.641401       0.394815       0.300591       0.228575
std         0.246572       0.338277       0.079325       0.221108
min         0.000000       0.000000       0.000000       0.000000
25%         0.469388       0.000000       0.312500       0.024540
50%         0.693878       0.270000       0.312500       0.165644
75%         0.836735       0.750000       0.312500       0.392638
max         1.000000       1.000000       1.000000       1.000000

            gust_kph  air_quality_Carbon_Monoxide  air_quality_Ozone  \
count  107378.000000                107378.000000      107378.000000
mean        0.053411                     0.011003           0.127462
std         0.040495                     0.021102           0.066110
min         0.000000                     0.000000           0.000000
25%         0.024656                     0.003943           0.085292
50%         0.043872                     0.006322           0.120657
75%         0.075054                     0.010851           0.162263
max         1.000000                     1.000000           1.000000

       air_quality_Nitrogen_dioxide  air_quality_Sulphur_dioxide  \
count                 107378.000000                107378.000000
mean                       0.036464                     0.021189
std                        0.059301                     0.046872
min                        0.000000                     0.000000
25%                        0.003460                     0.001774
50%                        0.012111                     0.004613
75%                        0.041957                     0.017033
max                        1.000000                     1.000000

       air_quality_PM2.5  air_quality_PM10
count      107378.000000     107378.000000
mean            0.015571          0.008476
std             0.024457          0.026236
min             0.000000          0.000000
25%             0.004366          0.001695
50%             0.008951          0.003467
75%             0.017679          0.007235
max             1.000000          1.000000

## Aggregate or Filter Data
Aggregate the data by computing monthly averages for temperature to prepare it for further analysis.

In [168]:
df['month'] = df['last_updated'].dt.month

print(df[['last_updated', 'month']].head())

         last_updated  month
0 2024-05-16 13:15:00      5
1 2024-05-16 10:45:00      5
2 2024-05-16 09:45:00      5
3 2024-05-16 10:45:00      5
4 2024-05-16 09:45:00      5

In [169]:
monthly_avg_temp = df.groupby(['country', 'month'])['temperature_celsius'].mean().reset_index()

print(monthly_avg_temp.head())

       country  month  temperature_celsius
0  Afghanistan      1             0.353750
1  Afghanistan      2             0.400665
2  Afghanistan      3             0.497889
3  Afghanistan      4             0.646244
4  Afghanistan      5             0.670743

### Data Cleaning and Preprocessing Summary Report

This report details the data cleaning and preprocessing steps applied to the 'Global_Weather_Repository.csv' dataset, aiming to prepare it for further analysis.

#### **Data Loading and Initial Inspection**
The dataset 'master_dataset.csv' was loaded into a pandas DataFrame named `df`. Initial inspection involved using `df.info()` to understand column data types and non-null counts, `df.head()` to view the first few rows, and `df.describe()` to obtain descriptive statistics for numerical columns. This step provided a foundational understanding of the dataset's structure and potential issues.

#### **Missing Value and Anomaly Handling**
Initially, `df.isnull().sum()` reported no missing values, but `df.describe()` and manual checks revealed sentinel values like -9999 and -1848.15 in air quality columns (`air_quality_Carbon_Monoxide`, `air_quality_Sulphur_dioxide`, `air_quality_PM10`). These erroneous values were explicitly replaced with `np.nan`.

Furthermore, extreme outliers in wind-related columns (`wind_mph`, `wind_kph`, `gust_mph`, `gust_kph`) exceeding 200 mph (approx 320 kph) and pressure columns (`pressure_mb`, `pressure_in`) outside the range of 850-1080 mb were also identified and converted to `np.nan`.

Finally, all introduced `np.nan` values across the air quality, wind, and pressure columns were imputed using the median value of their respective columns. This strategy was chosen to fill missing data without introducing bias from extreme values.

#### **Data Type Conversions**
Several columns underwent data type conversions to ensure proper handling and analysis:
*   The 'last_updated' column was converted to datetime objects using `pd.to_datetime` with the format '%Y-%m-%d %H:%M'.
*   'sunrise', 'sunset', 'moonrise', and 'moonset' columns, initially object type, were converted to datetime objects using `pd.to_datetime` with the format '%I:%M %p'.
*   The 'moon_phase' column was converted to a categorical data type (`category`) to optimize memory usage and accurately represent its discrete nature.

#### **Unit Standardization**
To standardize the dataset to metric units and remove redundant columns, the following imperial unit columns were dropped from the DataFrame:
*   `temperature_fahrenheit`
*   `wind_mph`
*   `pressure_in`
*   `precip_in`
*   `visibility_miles`
*   `gust_mph`

#### **Value Normalization**
Min-Max scaling was applied to several key numerical features to transform their values into a common range between 0 and 1. This normalization is crucial for algorithms sensitive to the scale of input features. The normalized columns include:
`temperature_celsius`, `wind_kph`, `pressure_mb`, `precip_mm`, `humidity`, `cloud`, `visibility_km`, `uv_index`, `gust_kph`, `air_quality_Carbon_Monoxide`, `air_quality_Ozone`, `air_quality_Nitrogen_dioxide`, `air_quality_Sulphur_dioxide`, `air_quality_PM2.5`, and `air_quality_PM10`.

#### **Data Aggregation**
For further analysis, a new 'month' column was extracted from the 'last_updated' datetime column. The data was then aggregated by 'country' and 'month' to calculate the monthly average of 'temperature_celsius', providing a summary view of temperature trends.

This comprehensive cleaning and preprocessing ensures the dataset is now consistent, free from critical anomalies, standardized, and ready for robust statistical analysis and model training.

## Save the Cleaned Data

### Subtask:
Save the cleaned and processed DataFrame to a new CSV file.

**Reasoning**:
As per instruction 1 and 2, I will save the cleaned and processed `df` DataFrame to a new CSV file named 'cleaned_global_weather_data.csv', ensuring that the DataFrame index is not included in the output file.

In [170]:
df.to_csv('cleaned_global_weather_data.csv', index=False)

## Final Task

### Subtask:
Conclude the data preparation, indicating that the dataset is now clean and ready for deeper analysis.

## Summary:

### Q&A
The data cleaning and preprocessing steps undertaken for the 'Global_Weather_Repository.csv' dataset involved initial inspection, robust handling of missing values and anomalies, data type conversions for consistency, unit standardization, value normalization, and data aggregation.

### Data Analysis Key Findings
*   **Initial Data Inspection:** The dataset `master_dataset.csv` was loaded and inspected using `df.info()`, `df.head()`, and `df.describe()` to understand its structure and statistics.
*   **Missing Value and Anomaly Handling:**
    *   Sentinel values like -9999 and -1848.15 were identified in air quality columns (`air_quality_Carbon_Monoxide`, `air_quality_Sulphur_dioxide`, `air_quality_PM10`) and replaced with `np.nan`.
    *   Extreme outliers in wind-related columns (exceeding \$200 \text{ mph}) and pressure columns (outside \$850-1080 \text{ mb}) were also converted to `np.nan`.
    *   All introduced `np.nan` values across these affected columns were imputed using their respective column medians.
*   **Data Type Conversions:**
    *   `last_updated` was converted to datetime objects.
    *   `sunrise`, `sunset`, `moonrise`, and `moonset` were converted to datetime objects.
    *   `moon_phase` was converted to a categorical data type for efficiency.
*   **Unit Standardization:** Six imperial unit columns (`temperature_fahrenheit`, `wind_mph`, `pressure_in`, `precip_in`, `visibility_miles`, `gust_mph`) were dropped to standardize to metric units.
*   **Value Normalization:** Min-Max scaling was applied to 15 key numerical features (including `temperature_celsius`, `wind_kph`, `pressure_mb`, and various air quality metrics) to normalize their values between 0 and 1.
*   **Data Aggregation:** A new 'month' column was extracted, and the data was aggregated by 'country' and 'month' to calculate the monthly average of `temperature_celsius`.
*   **Cleaned Data Export:** The processed DataFrame was successfully saved as `'cleaned_global_weather_data.csv'` without the DataFrame index.

### Insights or Next Steps
*   The dataset is now meticulously cleaned, consistent, standardized, and free from critical anomalies, making it suitable for robust statistical analysis and machine learning model training.
*   The cleaned data can now be used for deeper exploratory data analysis to uncover trends, patterns, and correlations, or proceed directly to model building based on specific analytical objectives.